services:
  postgres:
    image: postgres:17-alpine
    container_name: product-service-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-product_svc_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-product_svc_password}
      POSTGRES_DB: ${POSTGRES_DB:-product_svc_db}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
