services:
  postgres:
    image: postgres:17-alpine
    container_name: order-service-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-order_svc_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-order_svc_password}
      POSTGRES_DB: ${POSTGRES_DB:-order_svc_db}
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
